# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeamyApp' do
  use_frameworks!

  # Pods for TeamyApp
    pod 'Firebase/Analytics'
    pod 'Firebase/InAppMessaging'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
end
